package com.gestion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.TreeMap;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.read.biff.BiffException;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

import org.apache.poi.hssf.OldExcelFormatException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

import com.sqlite.GestionBD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabil
 */
public class FenetrePrincipale extends JFrame {

	/**
	 * Creates new form FenetreP
	 */
	public FenetrePrincipale() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		panelTitre = new JPanel();
		jLabel1 = new JLabel();
		panelCentre = new JPanel();
		panelOptions = new JPanel();
		panelOption1 = new JPanel();
		boutonAjout = new JButton();
		boutonStat = new JButton();
		panelOption2 = new JPanel();
		boutonExportExcel = new JButton();
		boutonExportPdf = new JButton();
		panelTable = new JPanel();
		jScrollPane1 = new JScrollPane();
		jTable1 = new JTable();
		jMenuBar2 = new JMenuBar();
		jMenu3 = new JMenu();
		jMenu4 = new JMenu();
		importer = new JMenuItem("Importer");
		exporter = new JMenuItem("Exporter");
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
		jLabel1.setText("  LOGICIEL ACGM  ");
		jLabel1.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		panelTitre.add(jLabel1);

		getContentPane().add(panelTitre, java.awt.BorderLayout.PAGE_START);

		panelCentre.setLayout(new BoxLayout(panelCentre, BoxLayout.LINE_AXIS));

		panelOptions.setLayout(new BoxLayout(panelOptions, BoxLayout.Y_AXIS));

		panelOption1.setBorder(BorderFactory.createTitledBorder("Option 1"));
		panelOption1.setLayout(new BoxLayout(panelOption1, BoxLayout.Y_AXIS));

		boutonAjout.setText("Ajouter Etudiant");
		panelOption1.add(boutonAjout);

		boutonStat.setText("Statistiques");
		boutonStat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				boutonStatActionPerformed(evt);
			}
		});
		panelOption1.add(boutonStat);

		panelOptions.add(panelOption1);

		panelOption2.setBorder(BorderFactory.createTitledBorder("Option 2"));
		panelOption2.setLayout(new BoxLayout(panelOption2, BoxLayout.Y_AXIS));

		boutonExportExcel.setText("Exporter Excel");

		boutonExportExcel.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				
				
				JFrame parentFrame = new JFrame();
				//JFileChooser fileChooser = new JFileChooser();
				
				JFileChooser fileChooser = new JFileChooser();
		        FileNameExtensionFilter filter = new FileNameExtensionFilter("Microsoft Office Excel Format", "xls");
		        fileChooser.addChoosableFileFilter(filter);
		        TreeMap<String, ArrayList<Etudiant>> listeEtuByUE = new TreeMap<>();
		        
				
				
				fileChooser.setDialogTitle("Specify a file to save");   
				 
				int userSelection = fileChooser.showSaveDialog(parentFrame);
				
				if (userSelection == JFileChooser.APPROVE_OPTION) {
					//File fileToSave = fileChooser.getSelectedFile();
					

				    WorkbookSettings wbSettings = new WorkbookSettings();
				    wbSettings.setLocale(new Locale("fr", "FR"));

				    WritableWorkbook workbook;
				    
					try {
						listeEtuByUE = GestionBD.getEtudiantsPerUE(listeEtu);
						File fileToSave;
						if (fileChooser.getSelectedFile().getCanonicalPath().matches("[a-zA-Z0-9]*.xls"))
							 fileToSave = new File( fileChooser.getSelectedFile().getCanonicalPath());
						else
							 fileToSave = new File( fileChooser.getSelectedFile().getCanonicalPath() + ".xls");
						workbook = Workbook.createWorkbook(fileToSave, wbSettings);
						String s = fileToSave.toString();
						WriteExcel test = new WriteExcel();
						//test.setOutputFile(s+".xls");
						test.write(workbook, listeEtu, listeEtuByUE);
					} catch (WriteException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					} catch (ClassNotFoundException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					} catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				    
				    //GestionFichierExcelWithJxl.toExcel(jTable1, new File(fileToSave.getAbsolutePath()+".xls"));
				}
				
				
				
			}

		}); 

		panelOption2.add(boutonExportExcel);

		boutonExportPdf.setText("Exporter PDF");
		
		panelOption2.add(boutonExportPdf);

		panelOptions.add(panelOption2);

		panelCentre.add(panelOptions);

		panelTable.setBorder(BorderFactory.createTitledBorder("Liste des Etudiants"));
		panelTable.setLayout(new java.awt.GridLayout());


		jTable1.setModel(tableModel);
		jScrollPane1.setViewportView(jTable1);

		panelTable.add(jScrollPane1);

		panelCentre.add(panelTable);

		getContentPane().add(panelCentre, java.awt.BorderLayout.CENTER);

		jMenu3.setText("Fichier");
		jMenuBar2.add(jMenu3);
		jMenu3.add(importer);
		jMenu3.add(exporter);
		jMenu4.setText("Edition");
		jMenuBar2.add(jMenu4);
		setJMenuBar(jMenuBar2);

		boutonStat.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {

				FenetreStatistique fstat = new FenetreStatistique();
				fstat.show();

			}
		});

		importer.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				//FileExtensionFilterDemo f = new FileExtensionFilterDemo();
				showOpenFileDialog();
			}
		});

		pack();
	}// </editor-fold>                        

	private void boutonStatActionPerformed(java.awt.event.ActionEvent evt) {                                                 
		// TODO add your handling code here:
	}                                                

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FenetrePrincipale().setVisible(true);
			}
		});


	}

	private static void showOpenFileDialog() {

		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		//     fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("PDF Documents", "pdf"));
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("MS Office Documents", "docx", "xlsx", "pptx", "xls"));
		//     fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
		fileChooser.setAcceptAllFileFilterUsed(false);
		int result = fileChooser.showOpenDialog(fileChooser);

		if (result == JFileChooser.APPROVE_OPTION) {
			//File selectedFile = fileChooser.getSelectedFile();

			File selectedFile = fileChooser.getSelectedFile();
			
			
			try  {
				GestionFichierExcelWithPoi.dataBaseCreation();
				GestionFichierExcelWithPoi.ouvertureFichier(selectedFile.getAbsolutePath());
				listeEtu  = GestionBD.recupererEtudiants();
			} catch (OldExcelFormatException e) {
				try {
					GestionFichierExcelWithJxl.dataBaseCreation();
					GestionFichierExcelWithJxl.ouvertureFichier(selectedFile.getAbsolutePath());
				} catch (BiffException | ClassNotFoundException | SQLException | IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
			} catch (ClassNotFoundException | SQLException | InvalidFormatException | IOException e) {
				e.printStackTrace();
			}
			
			try {

				listeEtu  = GestionBD.recupererEtudiants();
				ArrayList<UE> listeChoix = new ArrayList<UE>();
				ArrayList<UE> listeImpo = new ArrayList<UE>();
				ArrayList<UE> listeCommun = new ArrayList<UE>();



				for (int i = 0; i < listeEtu.size(); i++){
					String nom = listeEtu.get(i).getNom();					
					String prenom = listeEtu.get(i).getPrenom();
					String mail = listeEtu.get(i).getMailPerso();
					String spe = listeEtu.get(i).getSpecialite();
					String redou ;
					if ( listeEtu.get(i).isRedoublant())
					{
						redou = "oui";
					}

					else
					{
						redou = "non";

					}
					String numero = listeEtu.get(i).getNumero();
					listeUE = GestionBD.getUeEtudiant(numero);



					for(UE ue : listeUE) {

						if (ue.getType().equals(UE.types.IMPOSEE))
							listeImpo.add(ue); 
						else if(ue.getType().equals(UE.types.COMMUN))
							listeCommun.add(ue); 
						else 
							listeChoix.add(ue);
					}



					Object[] data = {nom,prenom,mail,spe,redou,numero,
							listeCommun.get(0).isValide() ? "OUI" : "NON",
									listeCommun.get(1).isValide() ? "OUI" : "NON",
											listeImpo.get(0).getNom(),listeImpo.get(1).getNom(),
											listeImpo.get(2).getNom(),listeImpo.get(3).getNom(),
											listeChoix.get(0).getNom(),listeChoix.get(1).getNom(),
											listeChoix.get(2).getNom(),listeChoix.get(3).getNom()};


					tableModel.addRow(data);

					listeImpo.clear();
					listeChoix.clear();
					listeCommun.clear();

				}

				jTable1.setModel(tableModel);//new javax.swing.table.DefaultTableModel(data, entete));
				jScrollPane1.setViewportView(jTable1);
				jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
				
			} catch (ClassNotFoundException | SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
		else
		{
			System.out.println("erreur fichier!");
		}

	}



	// Variables declaration - do not modify                     
	private JButton boutonAjout;
	private JButton boutonExportExcel;
	private JButton boutonExportPdf;
	private JButton boutonStat;
	private JLabel jLabel1;
	private JMenu jMenu3,jMenu4;
	private JMenuBar jMenuBar2;
	private static JScrollPane jScrollPane1;
	private static JTable jTable1;
	private JPanel panelCentre;
	private JMenuItem exporter,importer ; 
	private JPanel panelOption1;
	private JPanel panelOption2;
	private JPanel panelOptions;
	private JPanel panelTable;
	private JPanel panelTitre;
	int count = 0;
	static Object[] objs = {"Nom", "Prenom","Mail","Specialite","Redoublant","Num Etudiant"
		,"UE Projet", "UE ter", "UE Imposée 1","UE Imposée 2","UE Imposée 3","UE Imposée 4"
		,"UE à choix 1","UE à choix 2","UE à choix 3","UE à choix 4"};
	static DefaultTableModel tableModel = new DefaultTableModel(objs,0);
	private static ArrayList<Etudiant> listeEtu;
	private static ArrayList<UE> listeUE ; 
	// End of variables declaration                   
}
